const COLOR_GREEN = 0xc4e6a0;
const COLOR_GREEN_STRONG = 0x86cb3c;
const COLOR_ORANGE = 0xf0c97c;
const COLOR_ORANGE_STRONG = 0xfac515;
const COLOR_RED = 0xf35f6d;
const COLOR_BLUE = 0x0000ff;
const COLOR_GRAY = 0x808080;
const COLOR_RED_STRONG = 0xf04438;

export {
  COLOR_GREEN,
  COLOR_GREEN_STRONG,
  COLOR_ORANGE,
  COLOR_ORANGE_STRONG,
  COLOR_RED,
  COLOR_RED_STRONG,
  COLOR_BLUE,
  COLOR_GRAY,
};
